[project]
name = "numtorch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "idx2numpy>=1.2.3",
    "matplotlib>=3.10.9",
    "matplotlib-backend-kitty>=2.1.2",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "pyyaml>=6.0.3",
]
