from nn.layers.base import Layer


class Recurrent(Layer):
    def __init__(self): ...

    def forward(self, X): ...

    def get_params(self): ...

    def save_state(self): ...

    def load_state(self): ...
